/** English taglines for seed projects (zh taglines live in seed.json). */
export const taglinesEn: Record<string, string> = {
  "photo-ai": "AI photo studio — professional shots from selfies",
  "interior-ai": "AI interior design and room rendering",
  superx: "X/Twitter growth: analytics, AI writing, scheduling",
  headshotly: "60 professional headshots in 10 minutes",
  photog: "AI product scene generation for e-commerce",
  rekalab: "One prompt, 60-second video",
  tydal: "SEO keyword research + automated publishing",
  mkdirs: "Launch an AI directory site boilerplate in 30 minutes",
  founderpal: "AI marketing toolkit for solo founders",
  "setter-ai": "WhatsApp AI for booking and sales conversations",
  coverlettergpt: "Cover letters tailored to job descriptions",
  summarify: "AI summaries for files and links",
  "handit-ai": "Open-source agent self-eval and prompt iteration",
  giselle: "Visual AI workflows driven by GitHub events",
  nativemind: "Local Ollama assistant in your browser",
  jaaz: "Open multimodal Magic Canvas creative agent",
  "openai-agents-sdk": "Python multi-agent workflow framework",
  ruflo: "Claude Code / Codex agent meta-harness",
  autoagent: "Zero-code natural language LLM agents",
  evoagentx: "Self-evolving agent workflow framework",
  magicpath: "AI-generated shippable UI components",
  "wei-zhi-shu": "LLM food diary and diet AI",
  podwise: "AI podcast notes and summaries",
  qrbtf: "AI artistic QR codes",
  "kitten-fill-light": "Photography fill-light utility — paid chart topper",
  "cal-ai": "Photo-based calorie estimates by a teen team",
  "gamma-app": "AI presentations and sites",
  "bolt-new": "Full-stack app generation in the browser",
};
